### ISSUE TITLE
Why is this function using invert operator to negate booleans?

### ISSUE THREAD

**Issue by luispedroemg** [atlanhq/atlan-python#237]
https://github.com/atlanhq/atlan-python/blob/c8aac6ea576b6ecd58a57437617e710a89caf60a/pyatlan/events/atlan_event_handler.py#L67
The line above is trying to use the "~" (invert) operator to negate booleans.
This is very bad, since it's probably not doing what you think it's doing, unless the values passed in are of the numpy's [numpy.bool_](https://numpy.org/doc/stable/reference/arrays.scalars.html#numpy.bool_) type.

For reference:
`~True == -2` 
and
`~False == -1`

Can we change this so it uses the `not` operator?

**Comment by cmgrote** [comment]
Thank you for spotting this!
