### ISSUE TITLE
pyatlan.client.atlan takes ~7 seconds to import

### ISSUE THREAD

**Issue by zholbrook-plaid** [atlanhq/atlan-python#310]
Running `import pyatlan.client.atlan` takes around 7 seconds to complete. This takes far longer than I'd expect import statements to normally take (usually I'd expect it to take a small fraction of a second, and most libraries we use, such as Airflow, pandas, standard libaries, and more are all very fast to import).

Importing the atlan client actually takes much longer than instantiating it or making an Atlan API request which is very surprising.

Here's a piece of code that replicates this:

```
import time

t1 = time.time()
from pyatlan.client.atlan import AtlanClient
t2 = time.time()
print("atlan client import time (seconds):", t2 - t1)

t3 = time.time()
client = AtlanClient()
t4 = time.time()
print("atlan client instantiation time (seconds):", t4 - t3)


from pyatlan.model.assets import Table
t5 = time.time()
x = client.asset.get_by_guid(asset_type=Table, guid="d3c4d7a3-bec1-490c-9705-83059ffbf085")
t6 = time.time()
print("atlan client get table by guid time (seconds):", t6 - t5)
```

It outputs this on my machine:
```
atlan client import time (seconds): 7.337576866149902
atlan client instantiation time (seconds): 0.003535032272338867
atlan client get table by guid time (seconds): 1.0856139659881592
```

I'm on a macbook pro intel cpu.

I've seen a few issues around the web that are related and give some indication that its due to how pydantic is being used:
https://github.com/atlanhq/atlan-python/issues/187
https://github.com/pydantic/pydantic/issues/6768
https://github.com/pydantic/pydantic/issues/7263

Is this something that can be optimized/fixed?

**Comment by Aryamanz29** [comment]
Hey @zholbrook-plaid, thank you for opening an issue!

Could you also share your installed `pyatlan` version with us, so that we can investigate further?

I've just double-checked with the snippet you provided, and here are the results:

```sh
(venv) ➜  ✗ pip show pyatlan
Name: pyatlan
Version: 2.1.7 (latest)
Summary: Atlan Python Client

atlan client import time (seconds): 3.320816993713379
atlan client instantiation time (seconds): 0.002034902572631836
atlan client get table by guid time (seconds): 0.479140043258667
```

I'm running this on a MacBook Pro M1 (16 GB RAM) ☝️

**Comment by zholbrook-plaid** [comment]
Hi @Aryamanz29 , I'm on pyatlan 2.1.6:

```
-> pip show pyatlan
Name: pyatlan
Version: 2.1.6
Summary: Atlan Python Client
```

**Comment by zholbrook-plaid** [comment]
FYI: I've upgraded to pyatlan `2.1.7` and it has similar results:

```
atlan client import time (seconds): 6.82206916809082
atlan client instantiation time (seconds): 0.0039980411529541016
atlan client get table by guid time (seconds): 1.0934627056121826
```

**Comment by javier-sanz** [comment]
So I am using 2.1.3 version an I am experiencing the same import delay.

**Comment by jc65536** [comment]
It's taking over 20 s for me. Also using 2.1.3. It looks like the main culprit is pydantic's `smart_deepcopy`.

Attached is a cProfile output. The python script profiled contained just a single line `import pyatlan.client.atlan`.

[atlan-prof.txt](https://github.com/user-attachments/files/16447726/atlan-prof.txt)

**Comment by Lux-CC** [comment]
@Aryamanz29 The latest pyatlan packages have the same issues. An import of DataProduct class takes 2.5-5 seconds, and an import of the AtlanClient class another 2-5 seconds (2 on a macbook, 5 on a simple lambda microVM). Lambda has an init timeout of ±10 seconds and we're sometimes hitting it with lambdas of ±2GB mem. 

This makes pyatlan near useless for lambda use.
