### ISSUE TITLE
Add option to configure HTTP proxy in AtlanClient

### ISSUE THREAD

**Issue by gaczm** [atlanhq/atlan-python#78]
Hey, would it be possible to add an option to configure HTTP proxy for AtlanClient? It's useful in some usecases, but I see no way of doing so at this moment

**Comment by cmgrote** [comment]
Indeed it may not currently be possible, but we'll look into adding the possibility.

**Comment by ErnestoLoma** [comment]
@gaczm the Requests library that we are using already supports [proxy configuration via environment variables](https://requests.readthedocs.io/en/latest/user/advanced/).

**Comment by ErnestoLoma** [comment]
We will add this to the documentation shortly.

**Comment by gaczm** [comment]
Downside of using environment variables is, that it is used for all HTTP connections done with the Requests library. I would need an option to specify proxy only for requests done by Pyatlan
